const Pdata = [
  {
    id: 1,
    link: "https://github.com/Setsudan/Pole-Anglais-light",
    img: "p1",
    title: "Pole Anglais",
    date: "16/10/2019",
    desc: "This project was in association with Filip Zafirovski, my English teacher by the time who wanted students to get a source of inspiration by publishing articles and/or their work. It was my very first web project, and was kind of hard to pull off but I still enjoyed it.Since for the very first time i coded for a project and not myself.",
    tags: "Loads of crap",
  },
  {
    id: 2,
    link: "https://project-i-art.web.app/",
    img: "p2",
    title: "Project I.Art",
    date: "03/07/2021",
    desc: "In France to go to college you have to get a diploma, which requires multiple exams to be validated. One of the subjects I had to do a presentation on was Art. I decided to create an idea around an Artificial Intelligence who would create art based on the likes and dislikes of the spectator. This panel is a website made for the occasion.",
    tags: "Html,Scss, & AOS librairie",
  },
  {
    id: 3,
    link: "https://hestia-immobilier.web.app/",
    img: "p3",
    title: "Hestia Real Estate",
    date: "18-26/10/2021",
    desc: "At the very start of my student life @hetic, They grouped student randomly to make a project. The subject of the project was to create an agency, a fake web-app and website that sells premium submarines to plus ultra rich people. For that project I designed the website of the agency, and the app for the complex.",
    tags: "Html & Scss",
  },
  {
    id: 4,
    link: "https://ethlny.web.app/Projects/",
    img: "p4",
    title: "EvL First Design",
    date: "30/10/2021",
    desc: "Before the design and dev of this portfolio, I had made a portfolio where I only putted my socials link. All of that because I had no idea of what to put on it. Even if I was satisfied with the first version it did not in any case represented the mood and emotion I wanted it to give. And so I gave birth to the actual design of the website on the 11/11/2021",
    tags: "Nextjs & Scss",
  },
  {
    id: 5,
    link: "https://kelly-barbosa-portfolio.web.app/#/",
    img: "p5",
    title: "Kelly's Portfolio",
    date: "03/07/2021",
    desc: "Sometimes after arriving at my college, I met a freshly made friend who wanted to publish her portfolio. She knew how to design and do plenty others thing. To She didn't really like to code and was making her website with Wix. To which I proposed to remake her website by coding it myself.",
    tags: "VueJs & Scss",
  },
  {
    id: 6,
    link: "https://ethlny.web.app",
    img: "p6",
    title: "EthLny V2",
    date: "11-12/11/2021",
    desc: "After doing the amazing portfolio of Kelly, I was kind of disappointed with my own. So I decided to remake a new design. Use a Random language, study the color psychology, searched a tagline. And TA-DA here it is, the website you're in right now is the result of 7 hours of researching, designing and coding and debugging.",
    tags: "ReactJs, Scss & AOS librairy",
  },
];
export default Pdata;
